version: "3.7"
services:
  gameserver:
    build:
      context: "./gameserverimage/"
    image: "iw4x:latest"
    container_name: "iw4x-server"
    restart: always
    environment:
      IW4X_ARGS: "--ac-disable -dedicated +set sv_lanonly 1 +set net_port 28960 +exec server.cfg +map_rotate"
    volumes:
      - "./data:/iw4x/server/"
    ports:
      - "28960:28960"
      - "28960:28960/udp"
  fileserver:
    build:
      context: "./fileserverimage/"
    image: "fileserver:latest"
    volumes:
    - ./files:/files:ro
    ports:
    - "80:80"