version: "3.7"
services:
  gameserver:
    build:
      context: "./gameserverimage/"
    image: "iw4x:latest"
    container_name: "iw4x-server"
    restart: always
    environment:
      IW4X_ARGS: "--ac-disable -dedicated +fs_game mods/kuc_mod +set sv_lanonly 1 +set net_port 28960 +exec server.cfg +map_rotate"
    volumes:
      - "./data:/iw4x/server/"
    ports:
      - "28960:28960"
      - "28960:28960/udp"
    networks:
      backend:
        ipv4_address: 172.16.1.100

  gameserveradmin:
    build:
      context: "./gameserveradmin/"
    image: "iw4x-admin:latest"
    container_name: "iw4x-admin"
    restart: always
    volumes:
      - "./data:/iw4x/server/"
      - "./gameserveradmin/CurrentDatabase:/iw4x/admin/Database"
    ports:
      - "1624:1624"
    networks:
      backend:
        ipv4_address: 172.16.1.101

networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24